remote_theme: "mmistakes/minimal-mistakes@4.24.0"

# Plugins
plugins:
  - jekyll-include-cache

# Site title and description
title: Bar Storey
description: "A concepetual art project exploring terroir and memory through spirits and cocktails."

# Optional: Define navigation links
# This will be configured more in detail below
