remote_theme: "mmistakes/minimal-mistakes@4.24.0"

# Plugins
plugins:
  - jekyll-include-cache

# _config.yml

# Custom head script for Google Fonts
head:
  custom: [
    "<link href='https://fonts.googleapis.com/css?family=Josefin+Slab:400,700|Source+Sans+Pro:400,700&display=swap' rel='stylesheet'>"
  ]

# Site title and description
title: Bar Storey
description: "A concepetual art project exploring terroir and memory through spirits and cocktails."
