remote_theme: "mmistakes/minimal-mistakes@4.24.0"

# Plugins
plugins:
  - jekyll-include-cache

# Site title and description
title: Bar Storey
description: "A concepetual art project exploring terroir and memory through spirits and cocktails."

navigation:
  - title: "Home"
    url: "/"
  - title: "About"
    url: "/about/"
  - title: "Survey"
    url: "/survey/"
  - title: "Contact"
    url: "/contact/"
